// The seed asset is a contract between three places: `data.py`, Postgres, and
// this app. These tests hold the app's end of it.
//
// The id derivation matters most. `inventory_items.ingredient_id` is written
// offline against an id the app computed itself, and it has to satisfy a
// foreign key against a row Postgres created independently. If these drift,
// every queued insert fails on first sync — and it fails on a real phone,
// after the user has already added their shopping.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:shelflife_app/models/enums.dart';
import 'package:shelflife_app/models/ingredient.dart';
import 'package:shelflife_app/models/models.dart';

void main() {
  final raw =
      File('assets/seed/reference.json').readAsStringSync();
  final seed = jsonDecode(raw) as Map<String, dynamic>;

  List<Map<String, dynamic>> rows(String key) =>
      (seed[key] as List<dynamic>).cast<Map<String, dynamic>>();

  test('the asset holds the full catalogue', () {
    expect(rows('ingredients'), hasLength(65));
    expect(rows('aliases'), hasLength(153));
    expect(rows('recipes'), hasLength(40));
    expect(rows('products'), hasLength(40));
  });

  test('every ingredient id is md5(canonical_name) as a uuid', () {
    // The same value migration 006 makes Postgres compute. Hard-coded rather
    // than recomputed here on purpose: recomputing with the same algorithm
    // would pass even if the algorithm itself changed.
    final spinach = rows('ingredients')
        .firstWhere((i) => i['canonical_name'] == 'spinach');
    expect(spinach['id'], '76aba95c-ba4e-d128-0a1e-567b178f58a2');

    for (final row in rows('ingredients')) {
      expect(row['id'], matches(RegExp(r'^[0-9a-f]{8}-[0-9a-f]{4}-'
          r'[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')),
          reason: '${row['canonical_name']} has a malformed id');
    }
  });

  test('ids are unique across ingredients and across recipes', () {
    final ingredientIds = rows('ingredients').map((r) => r['id']).toSet();
    expect(ingredientIds, hasLength(rows('ingredients').length),
        reason: 'two ingredients share an id — an md5 collision or a '
            'duplicate canonical name');

    final recipeIds = rows('recipes').map((r) => r['id']).toSet();
    expect(recipeIds, hasLength(rows('recipes').length));
  });

  test('every recipe ingredient points at a real ingredient', () {
    final known = rows('ingredients').map((r) => r['id']).toSet();
    for (final recipe in rows('recipes')) {
      for (final line
          in (recipe['ingredients'] as List<dynamic>).cast<Map<String, dynamic>>()) {
        expect(known, contains(line['ingredient_id']),
            reason: '${recipe['name']} references '
                '${line['canonical_name']}, which is not in the catalogue');
      }
    }
  });

  test('every alias resolves to a canonical name', () {
    final names =
        rows('ingredients').map((r) => r['canonical_name']).toSet();
    for (final alias in rows('aliases')) {
      expect(names, contains(alias['canonical']),
          reason: '${alias['alias']} resolves to nothing');
    }
  });

  test('every product points at a real ingredient', () {
    final known = rows('ingredients').map((r) => r['id']).toSet();
    for (final product in rows('products')) {
      expect(known, contains(product['ingredient_id']),
          reason: '${product['product_name']} has no ingredient');
    }
  });

  test('every row parses into its model', () {
    // The asset is generated by Python and consumed by Dart. Field names and
    // enum spellings are the joint most likely thing to drift, and a shape
    // mismatch here would only show up as a crash on a real launch.
    for (final row in rows('ingredients')) {
      final ingredient = Ingredient.fromJson(row);
      expect(ingredient.canonicalName, isNotEmpty);
      expect(ingredient.glyphKey, isNotEmpty);
    }
    for (final row in rows('recipes')) {
      final recipe = Recipe.fromJson(row);
      expect(recipe.name, isNotEmpty);
      expect(recipe.methodSteps, isNotEmpty);
      expect(recipe.ingredients, isNotEmpty);
    }
    for (final row in rows('products')) {
      expect(Product.fromJson(row).barcode, isNotEmpty);
    }
  });

  test('every glyph_key resolves to a bundled asset', () {
    // The same guarantee tools/check_asset_coverage.py gives for the Figma
    // library, asserted against what is actually in the APK.
    final produce = Directory('assets/produce')
        .listSync()
        .map((f) => f.uri.pathSegments.last.replaceAll('.png', ''))
        .toSet();
    final glyphs = Directory('assets/glyph')
        .listSync()
        .map((f) => f.uri.pathSegments.last.replaceAll('.png', ''))
        .toSet();

    const categoryFallback = {
      'dairy': 'cat-dairy',
      'fruits': 'cat-fruits',
      'vegetables': 'cat-vegetables',
      'pantry': 'cat-pantry',
      'frozen': 'cat-frozen',
      'other': 'cat-pantry',
    };

    for (final row in rows('ingredients')) {
      final key = row['glyph_key'] as String;
      if (produce.contains(key)) continue;
      final fallback = categoryFallback[row['category']];
      expect(glyphs, contains(fallback),
          reason: '${row['canonical_name']} has glyph "$key", which has no '
              'render, and its category fallback "$fallback" is missing too');
    }
  });

  test('every seeded category is a category the app knows', () {
    final known = FoodCategory.values.map((c) => c.name).toSet();
    for (final row in rows('ingredients')) {
      expect(known, contains(row['category']),
          reason: '${row['canonical_name']} has category '
              '"${row['category']}", which FoodCategory does not define');
    }
  });
}
