"""ShelfLife reference data — the reviewable source of truth.

`generate.py` turns this into idempotent SQL. Edit here, never the generated
migrations.

Shelf life is in days per storage location; None means "not sensibly stored
this way". Prices are rough Indian retail rates for the ingredient's default
unit, used only for the estimated-value statistic and always labelled as an
estimate in the UI.

glyph_key must name an asset that exists in the Figma library — either one of
the 23 real renders or a category fallback.
"""

# Assets that actually exist in the Figma file (design/figma-v2.md).
REAL_GLYPHS = {
    "apple", "atta", "avocado", "banana", "broccoli", "capsicum", "carrot",
    "cauliflower", "coriander", "cream", "cucumber", "curd", "garlic",
    "ginger", "lemon", "milk", "onion", "paneer", "peas-frozen", "potato",
    "rice", "spinach", "tomato",
}
FALLBACK_GLYPHS = {"cat-dairy", "cat-fruits", "cat-vegetables", "cat-pantry", "cat-frozen"}

# name, category, unit, glyph, fridge, freezer, pantry, counter, price
INGREDIENTS = [
    # ---------------------------------------------------------- vegetables
    ("spinach",      "vegetables", "g",     "spinach",         6,   90, None, 2,   40),
    ("tomato",       "vegetables", "kg",    "tomato",          10,  None, None, 5,  40),
    ("onion",        "vegetables", "kg",    "onion",           30,  None, 45,  30,  35),
    ("potato",       "vegetables", "kg",    "potato",          21,  None, 40,  21,  30),
    ("cauliflower",  "vegetables", "head",  "cauliflower",     10,  60,  None, 3,   40),
    ("broccoli",     "vegetables", "head",  "broccoli",        8,   60,  None, 3,   80),
    ("capsicum",     "vegetables", "kg",    "capsicum",        12,  60,  None, 4,   80),
    ("carrot",       "vegetables", "kg",    "carrot",          21,  90,  None, 5,   50),
    ("cucumber",     "vegetables", "kg",    "cucumber",        7,   None, None, 3,  40),
    ("coriander",    "vegetables", "bunch", "coriander",       7,   30,  None, 2,   15),
    ("ginger",       "vegetables", "g",     "ginger",          21,  90,  30,  14,   30),
    ("garlic",       "vegetables", "g",     "garlic",          30,  180, 90,  30,   40),
    ("green chilli", "vegetables", "g",     "cat-vegetables",  14,  90,  None, 4,   20),
    ("okra",         "vegetables", "kg",    "cat-vegetables",  5,   60,  None, 2,   50),
    ("brinjal",      "vegetables", "kg",    "cat-vegetables",  7,   None, None, 3,  40),
    ("beans",        "vegetables", "kg",    "cat-vegetables",  7,   90,  None, 3,   60),
    ("cabbage",      "vegetables", "head",  "cat-vegetables",  14,  None, None, 4,  30),
    ("bottle gourd", "vegetables", "kg",    "cat-vegetables",  10,  None, None, 4,  30),
    ("curry leaves", "vegetables", "sprig", "cat-vegetables",  10,  90,  None, 3,   10),
    ("mushroom",     "vegetables", "g",     "cat-vegetables",  6,   None, None, 2,  60),
    ("spring onion", "vegetables", "bunch", "cat-vegetables",  8,   60,  None, 2,   25),
    ("peas",         "vegetables", "g",     "peas-frozen",     5,   180, None, 2,   40),

    # -------------------------------------------------------------- fruits
    ("banana",       "fruits", "pcs",   "banana",       7,   None, None, 4,   50),
    ("apple",        "fruits", "kg",    "apple",        30,  None, None, 7,  150),
    ("lemon",        "fruits", "pcs",   "lemon",        21,  None, None, 7,   10),
    ("avocado",      "fruits", "pcs",   "avocado",      7,   None, None, 3,   90),
    ("mango",        "fruits", "kg",    "cat-fruits",   7,   180, None, 4,  100),
    ("orange",       "fruits", "kg",    "cat-fruits",   21,  None, None, 7,   80),
    ("grapes",       "fruits", "g",     "cat-fruits",   10,  90,  None, 3,   80),
    ("pomegranate",  "fruits", "pcs",   "cat-fruits",   21,  None, None, 7,   60),
    ("papaya",       "fruits", "kg",    "cat-fruits",   7,   None, None, 3,   50),
    ("watermelon",   "fruits", "kg",    "cat-fruits",   10,  None, None, 5,   30),
    ("guava",        "fruits", "kg",    "cat-fruits",   10,  None, None, 4,   60),

    # --------------------------------------------------------------- dairy
    ("milk",         "dairy", "l",   "milk",        3,   30,  None, None, 60),
    ("curd",         "dairy", "g",   "curd",        7,   None, None, None, 40),
    ("paneer",       "dairy", "g",   "paneer",      5,   60,  None, None, 90),
    ("butter",       "dairy", "g",   "cat-dairy",   45,  180, None, None, 60),
    ("ghee",         "dairy", "g",   "cat-dairy",   180, None, 180, 180, 120),
    ("cheese",       "dairy", "g",   "cat-dairy",   21,  120, None, None, 120),
    ("cream",        "dairy", "ml",  "cream",       7,   None, None, None, 70),
    ("buttermilk",   "dairy", "ml",  "cat-dairy",   4,   None, None, None, 25),

    # -------------------------------------------------------------- pantry
    ("atta",          "pantry", "kg",  "atta",        None, None, 120, None, 250),
    ("rice",          "pantry", "kg",  "rice",        None, None, 365, None, 120),
    ("toor dal",      "pantry", "kg",  "cat-pantry",  None, None, 240, None, 160),
    ("moong dal",     "pantry", "kg",  "cat-pantry",  None, None, 240, None, 150),
    ("chana dal",     "pantry", "kg",  "cat-pantry",  None, None, 240, None, 140),
    ("sugar",         "pantry", "kg",  "cat-pantry",  None, None, 730, None,  50),
    ("salt",          "pantry", "kg",  "cat-pantry",  None, None, 999, None,  25),
    ("cooking oil",   "pantry", "l",   "cat-pantry",  None, None, 365, None, 140),
    ("tea",           "pantry", "g",   "cat-pantry",  None, None, 365, None, 200),
    ("coffee",        "pantry", "g",   "cat-pantry",  None, None, 240, None, 300),
    ("bread",         "pantry", "pcs", "cat-pantry",  7,    30,  3,   3,     50),
    ("eggs",          "pantry", "pcs", "cat-pantry",  28,   None, None, 7,    90),
    ("poha",          "pantry", "kg",  "cat-pantry",  None, None, 180, None,  60),
    ("besan",         "pantry", "kg",  "cat-pantry",  None, None, 180, None,  90),
    ("jaggery",       "pantry", "kg",  "cat-pantry",  None, None, 365, None,  70),
    ("garam masala",  "pantry", "g",   "cat-pantry",  None, None, 365, None,  80),
    ("turmeric",      "pantry", "g",   "cat-pantry",  None, None, 730, None,  40),
    ("cumin",         "pantry", "g",   "cat-pantry",  None, None, 730, None,  60),
    ("kasuri methi",  "pantry", "g",   "cat-pantry",  None, None, 365, None,  40),
    ("cashew",        "pantry", "g",   "cat-pantry",  180,  365, 120, None, 200),

    # -------------------------------------------------------------- frozen
    ("frozen peas",       "frozen", "g",   "peas-frozen", None, 180, None, None, 60),
    ("frozen paratha",    "frozen", "pcs", "cat-frozen",  None, 180, None, None, 80),
    ("ice cream",         "frozen", "ml",  "cat-frozen",  None, 120, None, None, 150),
    ("frozen vegetables", "frozen", "g",   "cat-frozen",  None, 180, None, None, 70),
]

# alias -> canonical name. Receipt OCR, typed input and recipe references all
# resolve through here (spec §3).
ALIASES = {
    # spinach
    "palak": "spinach", "paalak": "spinach", "baby spinach": "spinach",
    "spinach leaves": "spinach", "fresh spinach": "spinach",
    # tomato
    "tamatar": "tomato", "tomatoes": "tomato", "tomato local": "tomato",
    "desi tomato": "tomato", "hybrid tomato": "tomato",
    # onion
    "pyaz": "onion", "kanda": "onion", "onions": "onion",
    "red onion": "onion", "onion big": "onion",
    # potato
    "aloo": "potato", "alu": "potato", "potatoes": "potato", "batata": "potato",
    # cauliflower / broccoli
    "gobi": "cauliflower", "gobhi": "cauliflower", "phool gobi": "cauliflower",
    "brocolli": "broccoli", "brocoli": "broccoli",
    # capsicum
    "shimla mirch": "capsicum", "bell pepper": "capsicum",
    "green pepper": "capsicum", "capsicum green": "capsicum",
    # carrot / cucumber
    "gajar": "carrot", "carrots": "carrot",
    "kheera": "cucumber", "khira": "cucumber", "cucumbers": "cucumber",
    # coriander
    "dhania": "coriander", "hara dhania": "coriander", "cilantro": "coriander",
    "coriander leaves": "coriander",
    # ginger / garlic / chilli
    "adrak": "ginger", "ginger fresh": "ginger",
    "lehsun": "garlic", "lasun": "garlic", "garlic pods": "garlic",
    "hari mirch": "green chilli", "green chillies": "green chilli",
    "mirchi": "green chilli",
    # other veg
    "bhindi": "okra", "ladies finger": "okra", "okra fresh": "okra",
    "baingan": "brinjal", "eggplant": "brinjal", "aubergine": "brinjal",
    "french beans": "beans", "green beans": "beans",
    "patta gobi": "cabbage", "lauki": "bottle gourd", "doodhi": "bottle gourd",
    "kadi patta": "curry leaves", "mushrooms": "mushroom", "button mushroom": "mushroom",
    "hara pyaz": "spring onion", "matar": "peas", "green peas": "peas",
    # fruits
    "kela": "banana", "bananas": "banana", "robusta banana": "banana",
    "seb": "apple", "apples": "apple", "shimla apple": "apple",
    "nimbu": "lemon", "lime": "lemon", "lemons": "lemon",
    "avacado": "avocado", "avocados": "avocado", "butter fruit": "avocado",
    "aam": "mango", "santra": "orange", "oranges": "orange",
    "angoor": "grapes", "anar": "pomegranate", "papita": "papaya",
    "tarbooj": "watermelon", "amrud": "guava",
    # dairy
    "toned milk": "milk", "full cream milk": "milk", "amul taaza": "milk",
    "amul gold": "milk", "doodh": "milk", "cow milk": "milk",
    "milk 1l": "milk", "dahi": "curd", "yogurt": "curd", "yoghurt": "curd",
    "amul dahi": "curd", "cottage cheese": "paneer", "amul paneer": "paneer",
    "malai paneer": "paneer", "makhan": "butter", "amul butter": "butter",
    "clarified butter": "ghee", "desi ghee": "ghee",
    "amul cheese": "cheese", "cheese slices": "cheese",
    "fresh cream": "cream", "amul cream": "cream", "chaas": "buttermilk",
    "lassi": "buttermilk",
    # pantry
    "wheat flour": "atta", "aashirvaad atta": "atta", "chakki atta": "atta",
    "gehun ka atta": "atta", "basmati rice": "rice", "chawal": "rice",
    "sona masoori": "rice", "india gate rice": "rice",
    "arhar dal": "toor dal", "tuvar dal": "toor dal", "toor daal": "toor dal",
    "moong daal": "moong dal", "yellow moong dal": "moong dal",
    "chana daal": "chana dal", "bengal gram": "chana dal",
    "cheeni": "sugar", "shakkar": "sugar", "namak": "salt",
    "refined oil": "cooking oil", "sunflower oil": "cooking oil",
    "mustard oil": "cooking oil", "fortune oil": "cooking oil",
    "chai patti": "tea", "tata tea": "tea", "tea leaves": "tea",
    "instant coffee": "coffee", "bread loaf": "bread", "brown bread": "bread",
    "pav": "bread", "anda": "eggs", "egg": "eggs",
    "chiwda": "poha", "flattened rice": "poha",
    "gram flour": "besan", "gud": "jaggery",
    "garam masala powder": "garam masala", "haldi": "turmeric",
    "turmeric powder": "turmeric", "jeera": "cumin", "cumin seeds": "cumin",
    "methi": "kasuri methi", "dried fenugreek": "kasuri methi",
    "kaju": "cashew", "cashewnut": "cashew",
    # frozen
    "frozen matar": "frozen peas", "safal frozen peas": "frozen peas",
    "paratha frozen": "frozen paratha",
}

# name, prep_minutes, servings, difficulty, category, image_key, steps, ingredients
# ingredients: (canonical_name, quantity, unit, optional)
RECIPES = [
    ("Palak Paneer", 25, 4, "Easy", "main", "palak-paneer",
     ["Blanch the spinach for two minutes, then blend to a smooth puree.",
      "Fry the onion, ginger and garlic until golden.",
      "Add tomato and garam masala; cook until the oil separates.",
      "Stir in the spinach puree and simmer for five minutes.",
      "Fold in the paneer cubes and finish with cream."],
     [("spinach", 500, "g", False), ("paneer", 200, "g", False),
      ("onion", 2, "pcs", False), ("tomato", 1, "pcs", False),
      ("ginger", 1, "inch", False), ("garlic", 4, "cloves", False),
      ("garam masala", 1, "tsp", False), ("cream", 100, "ml", False),
      ("kasuri methi", 1, "tsp", False), ("cooking oil", 2, "tbsp", True)]),

    ("Aloo Gobi", 30, 4, "Easy", "main", "aloo-gobi",
     ["Cut the potato and cauliflower into even florets and cubes.",
      "Temper cumin in hot oil until it crackles.",
      "Add the potato, cover and cook until half done.",
      "Add cauliflower, turmeric and salt; cook uncovered until edges brown.",
      "Finish with coriander."],
     [("potato", 3, "pcs", False), ("cauliflower", 1, "head", False),
      ("onion", 1, "pcs", False), ("tomato", 1, "pcs", False),
      ("turmeric", 1, "tsp", False), ("cumin", 1, "tsp", False),
      ("coriander", 1, "bunch", False), ("cooking oil", 2, "tbsp", False),
      ("green chilli", 2, "pcs", True)]),

    ("Vegetable Pulao", 40, 4, "Easy", "main", "vegetable-pulao",
     ["Rinse and soak the rice for twenty minutes.",
      "Fry whole spices and onion in ghee until fragrant.",
      "Add the mixed vegetables and saute briefly.",
      "Add rice and water at one to one and a half, then bring to a boil.",
      "Cover and cook on low for twelve minutes, then rest before fluffing."],
     [("rice", 2, "cups", False), ("carrot", 1, "pcs", False),
      ("beans", 100, "g", False), ("peas", 100, "g", False),
      ("onion", 1, "pcs", False), ("ghee", 2, "tbsp", False),
      ("garam masala", 1, "tsp", False), ("cashew", 10, "pcs", True)]),

    ("Paneer Bhurji", 20, 3, "Easy", "main", "paneer-bhurji",
     ["Crumble the paneer coarsely.",
      "Saute onion, green chilli and ginger until soft.",
      "Add tomato and cook until pulpy.",
      "Stir in the crumbled paneer and turmeric; cook two minutes.",
      "Finish with coriander and a squeeze of lemon."],
     [("paneer", 250, "g", False), ("onion", 1, "pcs", False),
      ("tomato", 2, "pcs", False), ("green chilli", 2, "pcs", False),
      ("ginger", 1, "inch", False), ("turmeric", 0.5, "tsp", False),
      ("coriander", 1, "bunch", False), ("lemon", 0.5, "pcs", True)]),

    ("Avocado Toast", 10, 2, "Easy", "breakfast", "avocado-toast",
     ["Toast the bread until crisp.",
      "Mash the avocado with salt and lemon.",
      "Spread thickly and top with chilli flakes."],
     [("bread", 2, "pcs", False), ("avocado", 1, "pcs", False),
      ("lemon", 0.5, "pcs", False), ("salt", 1, "pinch", False),
      ("green chilli", 1, "pcs", True)]),

    # ---- remaining recipes reuse the five dish images by closest match ----
    ("Jeera Aloo", 20, 3, "Easy", "side", "aloo-gobi",
     ["Boil and cube the potatoes.", "Crackle cumin in hot oil.",
      "Toss the potatoes with turmeric and salt until coated.",
      "Finish with coriander."],
     [("potato", 4, "pcs", False), ("cumin", 1, "tsp", False),
      ("turmeric", 0.5, "tsp", False), ("coriander", 1, "bunch", False),
      ("cooking oil", 2, "tbsp", False)]),

    ("Palak Dal", 35, 4, "Easy", "main", "palak-paneer",
     ["Pressure cook the toor dal until soft.",
      "Saute garlic, cumin and green chilli.",
      "Add chopped spinach and wilt.",
      "Combine with the dal and simmer ten minutes."],
     [("toor dal", 1, "cup", False), ("spinach", 250, "g", False),
      ("garlic", 4, "cloves", False), ("cumin", 1, "tsp", False),
      ("turmeric", 0.5, "tsp", False), ("green chilli", 2, "pcs", True)]),

    ("Tomato Rasam", 25, 4, "Easy", "soup", "aloo-gobi",
     ["Simmer tomato with turmeric and salt.",
      "Add cooked toor dal and water.",
      "Temper cumin and curry leaves; pour over.",
      "Finish with coriander."],
     [("tomato", 4, "pcs", False), ("toor dal", 0.5, "cup", False),
      ("cumin", 1, "tsp", False), ("curry leaves", 2, "sprig", False),
      ("turmeric", 0.5, "tsp", False), ("coriander", 1, "bunch", True)]),

    ("Bhindi Masala", 25, 3, "Easy", "side", "aloo-gobi",
     ["Wash and dry the okra completely, then slice.",
      "Fry until the sliminess disappears.",
      "Add onion and tomato; cook down.",
      "Season with garam masala and salt."],
     [("okra", 400, "g", False), ("onion", 1, "pcs", False),
      ("tomato", 1, "pcs", False), ("garam masala", 1, "tsp", False),
      ("cooking oil", 3, "tbsp", False)]),

    ("Baingan Bharta", 40, 4, "Medium", "main", "aloo-gobi",
     ["Char the brinjal directly over flame until collapsed.",
      "Peel and mash the smoked flesh.",
      "Fry onion, ginger, garlic and tomato.",
      "Fold in the mashed brinjal and cook until dry.",
      "Finish with coriander."],
     [("brinjal", 1, "pcs", False), ("onion", 2, "pcs", False),
      ("tomato", 2, "pcs", False), ("ginger", 1, "inch", False),
      ("garlic", 4, "cloves", False), ("coriander", 1, "bunch", False),
      ("cooking oil", 3, "tbsp", False)]),

    ("Poha", 15, 2, "Easy", "breakfast", "vegetable-pulao",
     ["Rinse the poha briefly and drain.",
      "Temper mustard, curry leaves and green chilli.",
      "Add onion and potato; cook through.",
      "Fold in the poha with turmeric and salt.",
      "Finish with lemon and coriander."],
     [("poha", 2, "cups", False), ("onion", 1, "pcs", False),
      ("potato", 1, "pcs", False), ("curry leaves", 2, "sprig", False),
      ("turmeric", 0.5, "tsp", False), ("lemon", 0.5, "pcs", False),
      ("coriander", 1, "bunch", True), ("peas", 50, "g", True)]),

    ("Besan Chilla", 15, 2, "Easy", "breakfast", "avocado-toast",
     ["Whisk besan with water to a pourable batter.",
      "Stir in onion, tomato, chilli and coriander.",
      "Ladle onto a hot pan and spread thin.",
      "Cook both sides until golden."],
     [("besan", 1, "cup", False), ("onion", 1, "pcs", False),
      ("tomato", 1, "pcs", False), ("green chilli", 1, "pcs", False),
      ("coriander", 1, "bunch", False), ("turmeric", 0.5, "tsp", True)]),

    ("Masala Omelette", 10, 2, "Easy", "breakfast", "paneer-bhurji",
     ["Beat the eggs with salt.",
      "Add onion, tomato, chilli and coriander.",
      "Cook on a hot pan, folding once."],
     [("eggs", 3, "pcs", False), ("onion", 0.5, "pcs", False),
      ("tomato", 0.5, "pcs", False), ("green chilli", 1, "pcs", False),
      ("coriander", 1, "bunch", True)]),

    ("Matar Paneer", 30, 4, "Easy", "main", "paneer-bhurji",
     ["Blend onion and tomato into a smooth base.",
      "Cook the base until the oil separates.",
      "Add peas and simmer until tender.",
      "Add paneer and garam masala; rest before serving."],
     [("paneer", 200, "g", False), ("peas", 150, "g", False),
      ("onion", 2, "pcs", False), ("tomato", 2, "pcs", False),
      ("garam masala", 1, "tsp", False), ("cream", 50, "ml", True)]),

    ("Cabbage Poriyal", 20, 3, "Easy", "side", "aloo-gobi",
     ["Shred the cabbage finely.",
      "Temper mustard, curry leaves and chana dal.",
      "Add cabbage and cook uncovered until just tender."],
     [("cabbage", 1, "head", False), ("chana dal", 2, "tbsp", False),
      ("curry leaves", 2, "sprig", False), ("green chilli", 2, "pcs", False),
      ("cooking oil", 1, "tbsp", False)]),

    ("Lauki Sabzi", 25, 3, "Easy", "side", "aloo-gobi",
     ["Peel and cube the bottle gourd.",
      "Temper cumin, then add tomato and turmeric.",
      "Add the gourd, cover and cook until soft."],
     [("bottle gourd", 1, "pcs", False), ("tomato", 1, "pcs", False),
      ("cumin", 1, "tsp", False), ("turmeric", 0.5, "tsp", False),
      ("coriander", 1, "bunch", True)]),

    ("Carrot Halwa", 45, 4, "Medium", "dessert", "vegetable-pulao",
     ["Grate the carrots finely.",
      "Cook in milk until the liquid reduces almost fully.",
      "Add sugar and ghee; cook until glossy.",
      "Finish with cashews."],
     [("carrot", 1, "kg", False), ("milk", 1, "l", False),
      ("sugar", 1, "cup", False), ("ghee", 3, "tbsp", False),
      ("cashew", 15, "pcs", True)]),

    ("Cucumber Raita", 10, 4, "Easy", "side", "curd",
     ["Whisk the curd smooth.",
      "Grate the cucumber and squeeze out excess water.",
      "Fold together with cumin and salt."],
     [("curd", 400, "g", False), ("cucumber", 1, "pcs", False),
      ("cumin", 0.5, "tsp", False), ("coriander", 1, "bunch", True)]),

    ("Boondi Kadhi", 35, 4, "Medium", "main", "curd",
     ["Whisk curd with besan and turmeric until lump-free.",
      "Simmer gently, stirring, for twenty minutes.",
      "Temper cumin and curry leaves; pour over."],
     [("curd", 500, "g", False), ("besan", 4, "tbsp", False),
      ("turmeric", 0.5, "tsp", False), ("cumin", 1, "tsp", False),
      ("curry leaves", 2, "sprig", False)]),

    ("Mushroom Masala", 25, 3, "Easy", "main", "aloo-gobi",
     ["Clean and quarter the mushrooms.",
      "Fry onion, ginger and garlic until golden.",
      "Add tomato and cook down.",
      "Add mushrooms and cook until they release and reabsorb their liquid."],
     [("mushroom", 400, "g", False), ("onion", 1, "pcs", False),
      ("tomato", 2, "pcs", False), ("ginger", 1, "inch", False),
      ("garlic", 3, "cloves", False), ("garam masala", 1, "tsp", False)]),

    ("Paneer Tikka", 35, 4, "Medium", "starter", "paneer-bhurji",
     ["Marinate paneer and capsicum in spiced curd for twenty minutes.",
      "Thread onto skewers with onion.",
      "Grill or pan-sear until charred at the edges.",
      "Finish with lemon."],
     [("paneer", 250, "g", False), ("curd", 100, "g", False),
      ("capsicum", 1, "pcs", False), ("onion", 1, "pcs", False),
      ("garam masala", 1, "tsp", False), ("lemon", 0.5, "pcs", False)]),

    ("Dal Tadka", 30, 4, "Easy", "main", "aloo-gobi",
     ["Pressure cook toor dal with turmeric until soft.",
      "Heat ghee and crackle cumin, garlic and chilli.",
      "Pour the tempering over the dal.",
      "Finish with coriander."],
     [("toor dal", 1, "cup", False), ("ghee", 2, "tbsp", False),
      ("cumin", 1, "tsp", False), ("garlic", 4, "cloves", False),
      ("green chilli", 2, "pcs", False), ("turmeric", 0.5, "tsp", False),
      ("coriander", 1, "bunch", True)]),

    ("Moong Dal Khichdi", 30, 3, "Easy", "main", "vegetable-pulao",
     ["Rinse rice and moong dal together.",
      "Pressure cook with turmeric, salt and water.",
      "Temper cumin in ghee and stir through."],
     [("rice", 1, "cup", False), ("moong dal", 0.5, "cup", False),
      ("ghee", 2, "tbsp", False), ("cumin", 1, "tsp", False),
      ("turmeric", 0.5, "tsp", False), ("peas", 50, "g", True)]),

    ("Vegetable Upma", 20, 3, "Easy", "breakfast", "vegetable-pulao",
     ["Dry roast the poha lightly.",
      "Temper mustard, curry leaves and chana dal.",
      "Add onion, carrot and peas; cook briefly.",
      "Add water, then fold in the poha and cook covered."],
     [("poha", 1.5, "cups", False), ("onion", 1, "pcs", False),
      ("carrot", 1, "pcs", False), ("peas", 50, "g", False),
      ("curry leaves", 2, "sprig", False), ("cooking oil", 2, "tbsp", False)]),

    ("Tomato Onion Salad", 8, 2, "Easy", "salad", "cucumber",
     ["Slice tomato, onion and cucumber thinly.",
      "Dress with lemon, salt and coriander."],
     [("tomato", 2, "pcs", False), ("onion", 1, "pcs", False),
      ("cucumber", 1, "pcs", False), ("lemon", 0.5, "pcs", False),
      ("coriander", 1, "bunch", True)]),

    ("Aloo Paratha", 40, 4, "Medium", "breakfast", "aloo-gobi",
     ["Boil, peel and mash the potatoes.",
      "Season with chilli, coriander and salt.",
      "Stuff into atta dough rounds and roll gently.",
      "Cook on a hot tawa with ghee until spotted."],
     [("atta", 2, "cups", False), ("potato", 4, "pcs", False),
      ("green chilli", 2, "pcs", False), ("coriander", 1, "bunch", False),
      ("ghee", 2, "tbsp", False)]),

    ("Chana Dal Sundal", 25, 4, "Easy", "side", "aloo-gobi",
     ["Soak and boil the chana dal until just firm.",
      "Temper mustard, curry leaves and chilli.",
      "Toss the dal through and season."],
     [("chana dal", 1, "cup", False), ("curry leaves", 2, "sprig", False),
      ("green chilli", 2, "pcs", False), ("cooking oil", 1, "tbsp", False)]),

    ("Paneer Butter Masala", 35, 4, "Medium", "main", "palak-paneer",
     ["Blend tomato, cashew, ginger and garlic into a smooth base.",
      "Cook the base in butter until deep red.",
      "Add cream and garam masala.",
      "Fold in paneer and finish with kasuri methi."],
     [("paneer", 250, "g", False), ("tomato", 4, "pcs", False),
      ("cashew", 12, "pcs", False), ("butter", 40, "g", False),
      ("cream", 80, "ml", False), ("garam masala", 1, "tsp", False),
      ("kasuri methi", 1, "tsp", False), ("ginger", 1, "inch", False),
      ("garlic", 4, "cloves", False)]),

    ("Green Beans Stir Fry", 18, 3, "Easy", "side", "aloo-gobi",
     ["Trim and chop the beans small.",
      "Temper mustard and chana dal.",
      "Add beans with a splash of water and cook covered until tender."],
     [("beans", 300, "g", False), ("chana dal", 1, "tbsp", False),
      ("curry leaves", 2, "sprig", False), ("cooking oil", 1, "tbsp", False)]),

    ("Masala Chai", 10, 2, "Easy", "beverage", "curd",
     ["Boil water with crushed ginger and tea leaves.",
      "Add milk and sugar; bring to a rolling boil.",
      "Strain and serve."],
     [("tea", 2, "tsp", False), ("milk", 200, "ml", False),
      ("sugar", 2, "tsp", False), ("ginger", 0.5, "inch", False)]),

    ("Banana Smoothie", 8, 2, "Easy", "beverage", "curd",
     ["Blend banana, curd and milk until smooth.",
      "Sweeten with jaggery to taste."],
     [("banana", 2, "pcs", False), ("curd", 150, "g", False),
      ("milk", 150, "ml", False), ("jaggery", 1, "tbsp", True)]),

    ("Apple Cinnamon Porridge", 15, 2, "Easy", "breakfast", "curd",
     ["Simmer poha in milk until thickened.",
      "Grate in the apple and sweeten with jaggery."],
     [("poha", 1, "cup", False), ("milk", 400, "ml", False),
      ("apple", 1, "pcs", False), ("jaggery", 1, "tbsp", False)]),

    ("Cheese Toast", 10, 2, "Easy", "snack", "avocado-toast",
     ["Butter the bread lightly.",
      "Layer cheese, tomato and chilli.",
      "Grill until bubbling."],
     [("bread", 4, "pcs", False), ("cheese", 60, "g", False),
      ("tomato", 1, "pcs", False), ("butter", 10, "g", False),
      ("green chilli", 1, "pcs", True)]),

    ("Capsicum Rice", 25, 3, "Easy", "main", "vegetable-pulao",
     ["Cook and cool the rice.",
      "Saute capsicum and onion until blistered.",
      "Fold the rice through with garam masala."],
     [("rice", 2, "cups", False), ("capsicum", 2, "pcs", False),
      ("onion", 1, "pcs", False), ("garam masala", 1, "tsp", False),
      ("cooking oil", 2, "tbsp", False)]),

    ("Spinach Soup", 25, 4, "Easy", "soup", "palak-paneer",
     ["Wilt the spinach with garlic.",
      "Blend smooth with a little milk.",
      "Reheat gently and season."],
     [("spinach", 400, "g", False), ("garlic", 3, "cloves", False),
      ("milk", 200, "ml", False), ("butter", 15, "g", True)]),

    ("Frozen Peas Pulao", 25, 3, "Easy", "main", "vegetable-pulao",
     ["Soak the rice twenty minutes.",
      "Fry onion and whole spices in ghee.",
      "Add frozen peas straight from the freezer.",
      "Add rice and water; cook covered on low."],
     [("rice", 2, "cups", False), ("frozen peas", 150, "g", False),
      ("onion", 1, "pcs", False), ("ghee", 2, "tbsp", False),
      ("garam masala", 1, "tsp", False)]),

    ("Curd Rice", 15, 3, "Easy", "main", "curd",
     ["Mash warm cooked rice with curd and salt.",
      "Temper mustard, curry leaves and chilli.",
      "Stir through and rest before serving."],
     [("rice", 2, "cups", False), ("curd", 400, "g", False),
      ("curry leaves", 2, "sprig", False), ("green chilli", 1, "pcs", False),
      ("cooking oil", 1, "tbsp", False)]),

    ("Guava Chaat", 8, 2, "Easy", "snack", "cucumber",
     ["Cube the guava.",
      "Toss with lemon, salt and cumin."],
     [("guava", 2, "pcs", False), ("lemon", 0.5, "pcs", False),
      ("cumin", 0.5, "tsp", False), ("salt", 1, "pinch", False)]),

    ("Mango Lassi", 8, 2, "Easy", "beverage", "curd",
     ["Blend mango with curd and sugar.",
      "Thin with a little milk and chill."],
     [("mango", 1, "pcs", False), ("curd", 200, "g", False),
      ("sugar", 2, "tsp", False), ("milk", 100, "ml", True)]),

    ("Ghee Roast Paratha", 20, 2, "Easy", "breakfast", "aloo-gobi",
     ["Knead atta into a soft dough and rest.",
      "Roll into rounds and layer with ghee.",
      "Cook on a hot tawa until puffed."],
     [("atta", 2, "cups", False), ("ghee", 3, "tbsp", False),
      ("salt", 1, "pinch", False)]),
]

# barcode, product_name, brand, ingredient, category, pack_size
# Seeded Indian FMCG barcodes (D1: cache ships populated and grows from users).
PRODUCTS = [
    ("8901030865278", "Amul Taaza Toned Milk",    "Amul",         "milk",     "dairy",  "1 L"),
    ("8901030700033", "Amul Gold Full Cream Milk","Amul",         "milk",     "dairy",  "1 L"),
    ("8901030815010", "Amul Masti Dahi",          "Amul",         "curd",     "dairy",  "400 g"),
    ("8901030612345", "Amul Fresh Paneer",        "Amul",         "paneer",   "dairy",  "200 g"),
    ("8901030500019", "Amul Butter",              "Amul",         "butter",   "dairy",  "500 g"),
    ("8901030410017", "Amul Fresh Cream",         "Amul",         "cream",    "dairy",  "250 ml"),
    ("8901030320019", "Amul Cheese Slices",       "Amul",         "cheese",   "dairy",  "200 g"),
    ("8901491101813", "Aashirvaad Shudh Chakki Atta", "Aashirvaad","atta",    "pantry", "5 kg"),
    ("8901491234567", "Aashirvaad Select Atta",   "Aashirvaad",   "atta",     "pantry", "10 kg"),
    ("8906002501013", "India Gate Basmati Rice",  "India Gate",   "rice",     "pantry", "5 kg"),
    ("8906002502010", "India Gate Feast Rozzana", "India Gate",   "rice",     "pantry", "1 kg"),
    ("8901719104568", "Tata Salt",                "Tata",         "salt",     "pantry", "1 kg"),
    ("8901719110019", "Tata Tea Premium",         "Tata",         "tea",      "pantry", "500 g"),
    ("8901058000023", "Nescafe Classic",          "Nestle",       "coffee",   "pantry", "100 g"),
    ("8901063013016", "Britannia Brown Bread",    "Britannia",    "bread",    "pantry", "400 g"),
    ("8901063092013", "Britannia Whole Wheat Bread","Britannia",  "bread",    "pantry", "400 g"),
    ("8901725121013", "Fortune Sunlite Refined Oil","Fortune",    "cooking oil","pantry","1 L"),
    ("8901725133016", "Fortune Kachi Ghani Mustard Oil","Fortune","cooking oil","pantry","1 L"),
    ("8901030360015", "Amul Pure Ghee",           "Amul",         "ghee",     "pantry", "500 ml"),
    ("8901396111114", "Everest Garam Masala",     "Everest",      "garam masala","pantry","100 g"),
    ("8901396222227", "Everest Turmeric Powder",  "Everest",      "turmeric", "pantry", "200 g"),
    ("8901396333330", "Everest Jeera Whole",      "Everest",      "cumin",    "pantry", "100 g"),
    ("8901052041018", "Tata Sampann Toor Dal",    "Tata Sampann", "toor dal", "pantry", "1 kg"),
    ("8901052052014", "Tata Sampann Moong Dal",   "Tata Sampann", "moong dal","pantry", "1 kg"),
    ("8901052063010", "Tata Sampann Chana Dal",   "Tata Sampann", "chana dal","pantry", "1 kg"),
    ("8901052074016", "Tata Sampann Besan",       "Tata Sampann", "besan",    "pantry", "500 g"),
    ("8901764012341", "Madhur Pure Sugar",        "Madhur",       "sugar",    "pantry", "1 kg"),
    ("8904004400014", "Safal Frozen Green Peas",  "Safal",        "frozen peas","frozen","500 g"),
    ("8904004411010", "Safal Frozen Mixed Vegetables","Safal",    "frozen vegetables","frozen","500 g"),
    ("8901058853018", "Nestle A+ Slim Milk",      "Nestle",       "milk",     "dairy",  "1 L"),
    ("8901262010016", "Mother Dairy Toned Milk",  "Mother Dairy", "milk",     "dairy",  "500 ml"),
    ("8901262021012", "Mother Dairy Dahi",        "Mother Dairy", "curd",     "dairy",  "400 g"),
    ("8901262032019", "Mother Dairy Paneer",      "Mother Dairy", "paneer",   "dairy",  "200 g"),
    ("8901262043015", "Mother Dairy Butter",      "Mother Dairy", "butter",   "dairy",  "100 g"),
    ("8901396444443", "Everest Kasuri Methi",     "Everest",      "kasuri methi","pantry","25 g"),
    ("8906010500011", "Nutraj Cashew W240",       "Nutraj",       "cashew",   "pantry", "250 g"),
    ("8901719220015", "Tata Sampann Poha",        "Tata Sampann", "poha",     "pantry", "500 g"),
    ("8901012000018", "Patanjali Jaggery",        "Patanjali",    "jaggery",  "pantry", "500 g"),
    ("8904004422016", "Safal Frozen Paratha",     "Safal",        "frozen paratha","frozen","5 pcs"),
    ("8901058111117", "Nestle Milkmaid",          "Nestle",       "milk",     "dairy",  "400 g"),
]
