#!/usr/bin/env python3
"""Emit seed migrations from data.py.

Validates first and refuses to write anything if a reference is broken — a
dangling ingredient name would otherwise fail silently at apply time, because
the generated SQL resolves names via subquery.

Generated SQL is idempotent (`on conflict do nothing`) and resolves ingredient
IDs by name rather than hardcoding UUIDs, so it can be re-run safely.

Usage:  python supabase/seed/generate.py
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import data  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "migrations"


def q(value) -> str:
    """SQL literal. Doubles single quotes; None becomes NULL."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def ing_id(name: str) -> str:
    """Subquery resolving a canonical name to its id."""
    return f"(select id from ingredients where canonical_name = {q(name)})"


def validate() -> list[str]:
    errors: list[str] = []
    names = {row[0] for row in data.INGREDIENTS}

    if len(names) != len(data.INGREDIENTS):
        errors.append("duplicate canonical_name in INGREDIENTS")

    allowed_glyphs = data.REAL_GLYPHS | data.FALLBACK_GLYPHS
    for row in data.INGREDIENTS:
        name, category, unit, glyph = row[0], row[1], row[2], row[3]
        if glyph not in allowed_glyphs:
            errors.append(f"ingredient '{name}': glyph '{glyph}' is not in the Figma library")
        if category not in {"dairy", "fruits", "vegetables", "pantry", "frozen", "other"}:
            errors.append(f"ingredient '{name}': invalid category '{category}'")
        if all(v is None for v in row[4:8]):
            errors.append(f"ingredient '{name}': no shelf life for any storage location")

    for alias, target in data.ALIASES.items():
        if target not in names:
            errors.append(f"alias '{alias}' targets unknown ingredient '{target}'")
        if alias in names:
            errors.append(f"alias '{alias}' collides with a canonical name")

    recipe_names = [r[0] for r in data.RECIPES]
    if len(set(recipe_names)) != len(recipe_names):
        errors.append("duplicate recipe name")

    for recipe in data.RECIPES:
        rname, prep, servings, _diff, _cat, image, steps, ings = recipe
        if prep <= 0:
            errors.append(f"recipe '{rname}': prep_minutes must be positive")
        if not steps:
            errors.append(f"recipe '{rname}': no method steps")
        if not ings:
            errors.append(f"recipe '{rname}': no ingredients")
        seen = set()
        for iname, _qty, _unit, _opt in ings:
            if iname not in names:
                errors.append(f"recipe '{rname}': unknown ingredient '{iname}'")
            if iname in seen:
                errors.append(f"recipe '{rname}': ingredient '{iname}' listed twice")
            seen.add(iname)
        if not any(not opt for *_x, opt in ings):
            errors.append(f"recipe '{rname}': every ingredient is optional, so it can never match")

    barcodes = [p[0] for p in data.PRODUCTS]
    if len(set(barcodes)) != len(barcodes):
        errors.append("duplicate barcode in PRODUCTS")
    for bc, pname, _brand, iname, _cat, _size in data.PRODUCTS:
        if not bc.isdigit():
            errors.append(f"barcode '{bc}' ({pname}) is not numeric")
        if iname not in names:
            errors.append(f"product '{pname}': unknown ingredient '{iname}'")

    return errors


def write_ingredients() -> int:
    lines = [
        "-- GENERATED by supabase/seed/generate.py from supabase/seed/data.py",
        "-- Do not edit. Change data.py and regenerate.",
        "",
        "-- Canonical ingredient catalogue (spec §3). Shelf life is per storage",
        "-- location; null means 'not sensibly stored this way'. Prices are rough",
        "-- Indian retail rates and are ALWAYS surfaced as estimates.",
        "insert into ingredients (canonical_name, category, default_unit, glyph_key,",
        "  shelf_life_fridge_days, shelf_life_freezer_days, shelf_life_pantry_days,",
        "  shelf_life_counter_days, est_price_inr) values",
    ]
    rows = []
    for name, cat, unit, glyph, fr, fz, pa, co, price in data.INGREDIENTS:
        rows.append(
            f"  ({q(name)}, {q(cat)}::food_category, {q(unit)}, {q(glyph)}, "
            f"{q(fr)}, {q(fz)}, {q(pa)}, {q(co)}, {q(price)})"
        )
    lines.append(",\n".join(rows))
    lines.append("on conflict (canonical_name) do nothing;")
    lines.append("")
    lines.append("-- Alias resolution: OCR text, typed names and recipe references all")
    lines.append("-- resolve through here. Aliases are globally unique so parsing is")
    lines.append("-- deterministic.")
    lines.append("insert into ingredient_aliases (ingredient_id, alias) values")
    arows = [
        f"  ({ing_id(target)}, {q(alias)})"
        for alias, target in sorted(data.ALIASES.items())
    ]
    lines.append(",\n".join(arows))
    lines.append("on conflict (alias) do nothing;")
    lines.append("")

    (OUT / "010_seed_ingredients.sql").write_text("\n".join(lines), encoding="utf-8")
    return len(data.INGREDIENTS), len(data.ALIASES)


def write_recipes() -> int:
    lines = [
        "-- GENERATED by supabase/seed/generate.py from supabase/seed/data.py",
        "-- Do not edit. Change data.py and regenerate.",
        "",
        "insert into recipes (name, prep_minutes, servings, difficulty, category,",
        "  method_steps, image_key) values",
    ]
    rows = []
    for name, prep, servings, diff, cat, image, steps, _ings in data.RECIPES:
        steps_json = "[" + ", ".join(
            '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"' for s in steps
        ) + "]"
        rows.append(
            f"  ({q(name)}, {prep}, {servings}, {q(diff)}, {q(cat)}, "
            f"{q(steps_json)}::jsonb, {q(image)})"
        )
    lines.append(",\n".join(rows))
    lines.append("on conflict (name) do nothing;")
    lines.append("")
    lines.append("-- Normalised ingredient rows (D5): FR-07 ranks by availability, which")
    lines.append("-- is a join against inventory. Optional rows never count toward the")
    lines.append("-- have/total match.")
    lines.append("insert into recipe_ingredients (recipe_id, ingredient_id, quantity, unit, optional) values")
    irows = []
    for name, _prep, _serv, _diff, _cat, _img, _steps, ings in data.RECIPES:
        for iname, qty, unit, opt in ings:
            irows.append(
                f"  ((select id from recipes where name = {q(name)}), "
                f"{ing_id(iname)}, {q(qty)}, {q(unit)}, {q(opt)})"
            )
    lines.append(",\n".join(irows))
    lines.append("on conflict (recipe_id, ingredient_id) do nothing;")
    lines.append("")

    (OUT / "011_seed_recipes.sql").write_text("\n".join(lines), encoding="utf-8")
    return len(data.RECIPES), len(irows)


def write_products() -> int:
    lines = [
        "-- GENERATED by supabase/seed/generate.py from supabase/seed/data.py",
        "-- Do not edit. Change data.py and regenerate.",
        "",
        "-- Seeded Indian FMCG barcodes. D1: no external API -- the cache ships",
        "-- populated and grows whenever a user names an unknown barcode.",
        "-- verified = true marks these as reference rows; user contributions are false.",
        "insert into products (barcode, product_name, brand, ingredient_id, category,",
        "  pack_size, verified) values",
    ]
    rows = []
    for bc, pname, brand, iname, cat, size in data.PRODUCTS:
        rows.append(
            f"  ({q(bc)}, {q(pname)}, {q(brand)}, {ing_id(iname)}, "
            f"{q(cat)}::food_category, {q(size)}, true)"
        )
    lines.append(",\n".join(rows))
    lines.append("on conflict (barcode) do nothing;")
    lines.append("")

    (OUT / "012_seed_products.sql").write_text("\n".join(lines), encoding="utf-8")
    return len(data.PRODUCTS)


def main() -> int:
    errors = validate()
    if errors:
        print(f"{len(errors)} validation error(s) — nothing written:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    n_ing, n_alias = write_ingredients()
    n_rec, n_ri = write_recipes()
    n_prod = write_products()

    real = sum(1 for r in data.INGREDIENTS if r[3] in data.REAL_GLYPHS)
    print("validation passed\n")
    print(f"  ingredients        {n_ing:>4}   ({real} with a real render, {n_ing - real} on a category fallback)")
    print(f"  aliases            {n_alias:>4}")
    print(f"  recipes            {n_rec:>4}")
    print(f"  recipe ingredients {n_ri:>4}   (avg {n_ri / n_rec:.1f} per recipe)")
    print(f"  products           {n_prod:>4}")
    print(f"\nwrote 010_seed_ingredients.sql, 011_seed_recipes.sql, 012_seed_products.sql")
    return 0


if __name__ == "__main__":
    sys.exit(main())
