// GENERATED by tools/gen_theme.py from design/tokens.json
// Do not edit. Change the Figma file, re-export tokens.json, regenerate.
//
// test/theme_tokens_test.dart re-reads tokens.json and fails if this file
// has drifted, so a hand-edit here cannot survive CI.

import 'package:flutter/material.dart';

/// Colours, spacing and type, straight from the design file.
abstract final class T {
  // ------------------------------------------------------------ colour
  static const Color accentBright = Color(0xFF12B981);  // accent/bright
  static const Color accentPrimary = Color(0xFF0A7A55);  // accent/primary
  static const Color cardBase = Color(0xFFFFFFFF);  // card/base
  static const Color cardSoft = Color(0xFFF7FBF9);  // card/soft
  static const Color infoBg = Color(0xFFE8F1FB);  // info/bg
  static const Color infoText = Color(0xFF1565C0);  // info/text
  static const Color overlayScrim = Color(0xFF0D2119);  // overlay/scrim
  static const Color pageBlush = Color(0xFFFDEDE6);  // page/blush
  static const Color pageCream = Color(0xFFFDF4EC);  // page/cream
  static const Color pageMint = Color(0xFFE9F6F0);  // page/mint
  static const Color produceBrown = Color(0xFFA9713C);  // produce/brown
  static const Color produceCream = Color(0xFFFBF3E4);  // produce/cream
  static const Color produceLeaf = Color(0xFF3FA45F);  // produce/leaf
  static const Color produceLeafDark = Color(0xFF1F7A45);  // produce/leaf-dark
  static const Color produceLeafLite = Color(0xFF7FCB8A);  // produce/leaf-lite
  static const Color produceOrange = Color(0xFFF0912B);  // produce/orange
  static const Color produceRed = Color(0xFFD8452F);  // produce/red
  static const Color produceRedLite = Color(0xFFF2705A);  // produce/red-lite
  static const Color produceShadow = Color(0xFF0E3A28);  // produce/shadow
  static const Color produceSpecular = Color(0xFFFFFFFF);  // produce/specular
  static const Color produceYellow = Color(0xFFF5C63C);  // produce/yellow
  static const Color stateAmberBg = Color(0xFFFDF0DC);  // state/amber-bg
  static const Color stateAmberText = Color(0xFF9A5B00);  // state/amber-text
  static const Color stateRedBg = Color(0xFFFDECEA);  // state/red-bg
  static const Color stateRedText = Color(0xFFC62828);  // state/red-text
  static const Color structureBorder = Color(0xFFE4EAE6);  // structure/border
  static const Color structureDivider = Color(0xFFEDF1EE);  // structure/divider
  static const Color textOnAccent = Color(0xFFFFFFFF);  // text/on-accent
  static const Color textPrimary = Color(0xFF16211C);  // text/primary
  static const Color textSecondary = Color(0xFF5C6B64);  // text/secondary
  static const Color tintLemon = Color(0xFFFBF3D9);  // tint/lemon
  static const Color tintMint = Color(0xFFE3F4EC);  // tint/mint
  static const Color tintPeach = Color(0xFFFCEBDD);  // tint/peach

  // ------------------------------------------------------- spacing / size
  static const double radiusCard = 24.0;  // radius/card
  static const double radiusPill = 999.0;  // radius/pill
  static const double radiusScreen = 42.0;  // radius/screen
  static const double radiusSheet = 30.0;  // radius/sheet
  static const double radiusTile = 18.0;  // radius/tile
  static const double sizeScreenH = 915.0;  // size/screen-h
  static const double sizeScreenW = 412.0;  // size/screen-w
  static const double sizeTapMin = 48.0;  // size/tap-min
  static const double space12 = 12.0;  // space/12
  static const double space16 = 16.0;  // space/16
  static const double space20 = 20.0;  // space/20
  static const double space24 = 24.0;  // space/24
  static const double space4 = 4.0;  // space/4
  static const double space8 = 8.0;  // space/8

  // --------------------------------------------------------------- type
  static const String fontFamily = 'Plus Jakarta Sans';

  static const TextStyle displayBold30 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w700, fontSize: 30.0, height: 1.2667);  // Display/Bold-30
  static const TextStyle displayBold26 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w700, fontSize: 26.0, height: 1.2692);  // Display/Bold-26
  static const TextStyle numeralBold34 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w700, fontSize: 34.0, height: 1.1765);  // Numeral/Bold-34
  static const TextStyle priceBold24 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w700, fontSize: 24.0, height: 1.2500);  // Price/Bold-24
  static const TextStyle titleSemiBold18 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w600, fontSize: 18.0, height: 1.3333);  // Title/SemiBold-18
  static const TextStyle sectionSemiBold16 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w600, fontSize: 16.0, height: 1.3750);  // Section/SemiBold-16
  static const TextStyle cardSemiBold15 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w600, fontSize: 15.0, height: 1.3333);  // Card/SemiBold-15
  static const TextStyle priceSemiBold15 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w600, fontSize: 15.0, height: 1.3333);  // Price/SemiBold-15
  static const TextStyle bodyRegular14 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w400, fontSize: 14.0, height: 1.4286);  // Body/Regular-14
  static const TextStyle secondaryRegular13 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w400, fontSize: 13.0, height: 1.3846);  // Secondary/Regular-13
  static const TextStyle labelMedium12 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w500, fontSize: 12.0, height: 1.3333);  // Label/Medium-12
  static const TextStyle chipSemiBold11 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w600, fontSize: 11.0, height: 1.2727);  // Chip/SemiBold-11
  static const TextStyle navMedium11 = TextStyle(fontFamily: fontFamily, fontWeight: FontWeight.w500, fontSize: 11.0, height: 1.2727);  // Nav/Medium-11
}

/// Freshness banding. Fresh deliberately has NO badge — silence means fine
/// (spec D4). Only two chips exist.
enum Freshness { fresh, soon, today }

/// The eight-point grid the whole layout sits on.
abstract final class Gap {
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 16;
  static const double lg = 24;
}
