#!/usr/bin/env python3
"""Generate the Flutter theme from design/tokens.json.

The point of generating rather than hand-typing: tokens.json was itself read
back out of Figma, so deriving Dart from it means the app cannot drift from the
design file. A hand-edit to the generated file is caught by
test/theme_tokens_test.dart, which re-reads tokens.json and compares.

Usage:  python tools/gen_theme.py
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
OUT = ROOT / "shelflife_app" / "lib" / "core" / "theme" / "tokens.g.dart"

# Weight names Figma uses -> Flutter FontWeight
WEIGHTS = {
    "Light": "w300", "Regular": "w400", "Medium": "w500",
    "SemiBold": "w600", "Bold": "w700", "ExtraBold": "w800",
}


def dart_name(key: str) -> str:
    """`surface/canvas` -> `surfaceCanvas`; `space/16` -> `space16`."""
    parts = re.split(r"[/\-_]", key)
    head, *rest = parts
    # lowerCamelCase: Dart lints require it for constants, and Figma style names
    # like "Display/Bold-30" start capitalised.
    head = head[:1].lower() + head[1:]
    return head + "".join(p[:1].upper() + p[1:] for p in rest)


def main() -> int:
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))
    colour = tokens["colour"]
    scale = tokens["scale"]
    types = tokens["type"]

    lines = [
        "// GENERATED by tools/gen_theme.py from design/tokens.json",
        "// Do not edit. Change the Figma file, re-export tokens.json, regenerate.",
        "//",
        "// test/theme_tokens_test.dart re-reads tokens.json and fails if this file",
        "// has drifted, so a hand-edit here cannot survive CI.",
        "",
        "import 'package:flutter/material.dart';",
        "",
        "/// Colours, spacing and type, straight from the design file.",
        "abstract final class T {",
        "  // ------------------------------------------------------------ colour",
    ]

    for key in sorted(colour):
        hexv = colour[key].lstrip("#")
        lines.append(f"  static const Color {dart_name(key)} = Color(0xFF{hexv});"
                     f"  // {key}")

    lines += ["", "  // ------------------------------------------------------- spacing / size"]
    for key in sorted(scale):
        val = scale[key]
        lines.append(f"  static const double {dart_name(key)} = {float(val)};"
                     f"  // {key}")

    lines += [
        "",
        "  // --------------------------------------------------------------- type",
        f"  static const String fontFamily = '{next(iter(types.values()))['family']}';",
        "",
    ]
    for name in types:
        t = types[name]
        weight = WEIGHTS.get(t["style"].replace(" ", ""), "w400")
        lines.append(
            f"  static const TextStyle {dart_name(name.replace('/', '-'))} = TextStyle("
            f"fontFamily: fontFamily, fontWeight: FontWeight.{weight}, "
            f"fontSize: {float(t['size'])}, height: {t['lineHeight'] / t['size']:.4f});"
            f"  // {name}"
        )

    lines += [
        "}",
        "",
        "/// Freshness banding. Fresh deliberately has NO badge — silence means fine",
        "/// (spec D4). Only two chips exist.",
        "enum Freshness { fresh, soon, today }",
        "",
        "/// The eight-point grid the whole layout sits on.",
        "abstract final class Gap {",
        "  static const double xs = 4;",
        "  static const double sm = 8;",
        "  static const double md = 16;",
        "  static const double lg = 24;",
        "}",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {len(colour)} colours, {len(scale)} scale values, {len(types)} text styles")
    # sanity: the two WCAG corrections must be present
    assert colour["accent/primary"] == "#0A7A55", "accent must be the AA-safe emerald (D14)"
    assert colour["state/amber-text"] == "#9A5B00", "amber must be the AA-safe v2 value"
    print("  D11 and D14 colour corrections confirmed present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
