-- GENERATED by supabase/seed/generate.py from supabase/seed/data.py
-- Do not edit. Change data.py and regenerate.

-- Seeded Indian FMCG barcodes. D1: no external API -- the cache ships
-- populated and grows whenever a user names an unknown barcode.
-- verified = true marks these as reference rows; user contributions are false.
insert into products (barcode, product_name, brand, ingredient_id, category,
  pack_size, verified) values
  ('8901030865278', 'Amul Taaza Toned Milk', 'Amul', (select id from ingredients where canonical_name = 'milk'), 'dairy'::food_category, '1 L', true),
  ('8901030700033', 'Amul Gold Full Cream Milk', 'Amul', (select id from ingredients where canonical_name = 'milk'), 'dairy'::food_category, '1 L', true),
  ('8901030815010', 'Amul Masti Dahi', 'Amul', (select id from ingredients where canonical_name = 'curd'), 'dairy'::food_category, '400 g', true),
  ('8901030612345', 'Amul Fresh Paneer', 'Amul', (select id from ingredients where canonical_name = 'paneer'), 'dairy'::food_category, '200 g', true),
  ('8901030500019', 'Amul Butter', 'Amul', (select id from ingredients where canonical_name = 'butter'), 'dairy'::food_category, '500 g', true),
  ('8901030410017', 'Amul Fresh Cream', 'Amul', (select id from ingredients where canonical_name = 'cream'), 'dairy'::food_category, '250 ml', true),
  ('8901030320019', 'Amul Cheese Slices', 'Amul', (select id from ingredients where canonical_name = 'cheese'), 'dairy'::food_category, '200 g', true),
  ('8901491101813', 'Aashirvaad Shudh Chakki Atta', 'Aashirvaad', (select id from ingredients where canonical_name = 'atta'), 'pantry'::food_category, '5 kg', true),
  ('8901491234567', 'Aashirvaad Select Atta', 'Aashirvaad', (select id from ingredients where canonical_name = 'atta'), 'pantry'::food_category, '10 kg', true),
  ('8906002501013', 'India Gate Basmati Rice', 'India Gate', (select id from ingredients where canonical_name = 'rice'), 'pantry'::food_category, '5 kg', true),
  ('8906002502010', 'India Gate Feast Rozzana', 'India Gate', (select id from ingredients where canonical_name = 'rice'), 'pantry'::food_category, '1 kg', true),
  ('8901719104568', 'Tata Salt', 'Tata', (select id from ingredients where canonical_name = 'salt'), 'pantry'::food_category, '1 kg', true),
  ('8901719110019', 'Tata Tea Premium', 'Tata', (select id from ingredients where canonical_name = 'tea'), 'pantry'::food_category, '500 g', true),
  ('8901058000023', 'Nescafe Classic', 'Nestle', (select id from ingredients where canonical_name = 'coffee'), 'pantry'::food_category, '100 g', true),
  ('8901063013016', 'Britannia Brown Bread', 'Britannia', (select id from ingredients where canonical_name = 'bread'), 'pantry'::food_category, '400 g', true),
  ('8901063092013', 'Britannia Whole Wheat Bread', 'Britannia', (select id from ingredients where canonical_name = 'bread'), 'pantry'::food_category, '400 g', true),
  ('8901725121013', 'Fortune Sunlite Refined Oil', 'Fortune', (select id from ingredients where canonical_name = 'cooking oil'), 'pantry'::food_category, '1 L', true),
  ('8901725133016', 'Fortune Kachi Ghani Mustard Oil', 'Fortune', (select id from ingredients where canonical_name = 'cooking oil'), 'pantry'::food_category, '1 L', true),
  ('8901030360015', 'Amul Pure Ghee', 'Amul', (select id from ingredients where canonical_name = 'ghee'), 'pantry'::food_category, '500 ml', true),
  ('8901396111114', 'Everest Garam Masala', 'Everest', (select id from ingredients where canonical_name = 'garam masala'), 'pantry'::food_category, '100 g', true),
  ('8901396222227', 'Everest Turmeric Powder', 'Everest', (select id from ingredients where canonical_name = 'turmeric'), 'pantry'::food_category, '200 g', true),
  ('8901396333330', 'Everest Jeera Whole', 'Everest', (select id from ingredients where canonical_name = 'cumin'), 'pantry'::food_category, '100 g', true),
  ('8901052041018', 'Tata Sampann Toor Dal', 'Tata Sampann', (select id from ingredients where canonical_name = 'toor dal'), 'pantry'::food_category, '1 kg', true),
  ('8901052052014', 'Tata Sampann Moong Dal', 'Tata Sampann', (select id from ingredients where canonical_name = 'moong dal'), 'pantry'::food_category, '1 kg', true),
  ('8901052063010', 'Tata Sampann Chana Dal', 'Tata Sampann', (select id from ingredients where canonical_name = 'chana dal'), 'pantry'::food_category, '1 kg', true),
  ('8901052074016', 'Tata Sampann Besan', 'Tata Sampann', (select id from ingredients where canonical_name = 'besan'), 'pantry'::food_category, '500 g', true),
  ('8901764012341', 'Madhur Pure Sugar', 'Madhur', (select id from ingredients where canonical_name = 'sugar'), 'pantry'::food_category, '1 kg', true),
  ('8904004400014', 'Safal Frozen Green Peas', 'Safal', (select id from ingredients where canonical_name = 'frozen peas'), 'frozen'::food_category, '500 g', true),
  ('8904004411010', 'Safal Frozen Mixed Vegetables', 'Safal', (select id from ingredients where canonical_name = 'frozen vegetables'), 'frozen'::food_category, '500 g', true),
  ('8901058853018', 'Nestle A+ Slim Milk', 'Nestle', (select id from ingredients where canonical_name = 'milk'), 'dairy'::food_category, '1 L', true),
  ('8901262010016', 'Mother Dairy Toned Milk', 'Mother Dairy', (select id from ingredients where canonical_name = 'milk'), 'dairy'::food_category, '500 ml', true),
  ('8901262021012', 'Mother Dairy Dahi', 'Mother Dairy', (select id from ingredients where canonical_name = 'curd'), 'dairy'::food_category, '400 g', true),
  ('8901262032019', 'Mother Dairy Paneer', 'Mother Dairy', (select id from ingredients where canonical_name = 'paneer'), 'dairy'::food_category, '200 g', true),
  ('8901262043015', 'Mother Dairy Butter', 'Mother Dairy', (select id from ingredients where canonical_name = 'butter'), 'dairy'::food_category, '100 g', true),
  ('8901396444443', 'Everest Kasuri Methi', 'Everest', (select id from ingredients where canonical_name = 'kasuri methi'), 'pantry'::food_category, '25 g', true),
  ('8906010500011', 'Nutraj Cashew W240', 'Nutraj', (select id from ingredients where canonical_name = 'cashew'), 'pantry'::food_category, '250 g', true),
  ('8901719220015', 'Tata Sampann Poha', 'Tata Sampann', (select id from ingredients where canonical_name = 'poha'), 'pantry'::food_category, '500 g', true),
  ('8901012000018', 'Patanjali Jaggery', 'Patanjali', (select id from ingredients where canonical_name = 'jaggery'), 'pantry'::food_category, '500 g', true),
  ('8904004422016', 'Safal Frozen Paratha', 'Safal', (select id from ingredients where canonical_name = 'frozen paratha'), 'frozen'::food_category, '5 pcs', true),
  ('8901058111117', 'Nestle Milkmaid', 'Nestle', (select id from ingredients where canonical_name = 'milk'), 'dairy'::food_category, '400 g', true)
on conflict (barcode) do nothing;
